apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-datasource
    access: proxy
    url: http://prometheus:9091
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

